-- users
CREATE TABLE users (
  id BIGSERIAL NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL DEFAULT 'user',
  deleted_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_users PRIMARY KEY (id)
);

-- posts
CREATE TABLE posts (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  user_id BIGINT NOT NULL,
  deleted_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_posts_users FOREIGN KEY (user_id) REFERENCES users(id)
);

-- comments
CREATE TABLE comments (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  content TEXT NOT NULL,
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL,
  deleted_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_comments_users FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_comments_posts FOREIGN KEY (post_id) REFERENCES posts(id)
);

-- test table
CREATE TABLE test (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  varchar_column VARCHAR(255) NOT NULL,
  varying_column VARCHAR(255) NOT NULL,
  text_column TEXT NOT NULL,
  smallint_column SMALLINT NOT NULL,
  integer_column INTEGER NOT NULL,
  bigint_column BIGINT NOT NULL,
  decimal_column DECIMAL(10, 2) NOT NULL,
  numeric_column NUMERIC(10, 2) NOT NULL,
  real_column REAL NOT NULL,
  double_precision_column DOUBLE PRECISION NOT NULL,
  boolean_column BOOLEAN NOT NULL DEFAULT FALSE,
  timestamp_column TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  timestamp_with_timezone_column TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);